autores/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.registro_view, name='registro'),
]

panos_de_prato/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'panos'

urlpatterns = [
    path('', views.home, name='home'),
    path('panos_de_prato/categoria/<int:categoria_id>/', views.categoria, name='categoria'),
    path('panos_de_prato/<int:id>/', views.pano, name='pano'),
    path('panos_de_prato/procurar/', views.procurar, name='procurar'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panos_de_prato.urls')),
    path('autores/', include('autores.urls')),
]

autores/models.py
from django.db import models

# Create your models here.

panos_de_prato/models.py
from django.db import models
from django.contrib.auth.models import User

class  Categoria(models.Model):
    nome = models.CharField(max_length=65)

    def __str__(self):
        return self.nome

class Panos(models.Model):
    titulo = models.CharField(max_length=65)
    descricao = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preco = models.DecimalField(max_digits=4, decimal_places=2)
    unidade_preco = models.CharField(max_length=10)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    esta_publicado = models.BooleanField(default=False)
    pano_imagem = models.ImageField(upload_to='panos_de_prato/panos_imagens/%d/%m/%Y/', 
                                    blank=True, default=''
                                    )
    categoria = models.ForeignKey(
        Categoria, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    autor = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.titulo

autores/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistroForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

autores/views.py
from django.shortcuts import render
from autores.forms import RegistroForm

def registro_view(request):
    if request.POST:
        formulario = RegistroForm(request.POST)
    else:
        formulario = RegistroForm()

    return render(request, 'registro_view.html', {
        'form': formulario,
    })

panos_de_prato/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Panos
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from utils.paginacao import make_pagination_range

def home(request):
    panos = Panos.objects.filter(esta_publicado=True).order_by('-id')

    try:
        pagina_atual = int(request.GET.get('page', 1))
    except ValueError:
        pagina_atual = 1

    paginador = Paginator(panos, 6)
    pagina_objeto = paginador.get_page(pagina_atual)
    range_paginacao = make_pagination_range(
        paginador.page_range,
        4,
        pagina_atual,
    )

    return render(request, 'home.html', context={
        'panos': pagina_objeto,
        'range_paginacao': range_paginacao,
    })

def pano(request, id):
    pano = get_object_or_404(Panos, pk=id, esta_publicado=True)
    return render(request, 'panos-view.html', context={
        'pano': pano,
        'is_detail_page': True,
        })

def categoria(request, categoria_id):
    panos = get_list_or_404(Panos.objects.filter(categoria__id=categoria_id, esta_publicado=True).order_by('-id'))
    return render(request, 'categoria.html', context={
        'panos': panos,
        'titulo': f'{panos[0].categoria.nome} - Categoria | ',
    })

def procurar(request):
    termo_procurado = request.GET.get('q','').strip()

    if not termo_procurado:
        raise Http404()
    
    panos = Panos.objects.filter(
        Q(
            Q(titulo__icontains=termo_procurado) | 
            Q(descricao__icontains=termo_procurado),
        ),
        esta_publicado=True,
    ).order_by('-titulo')

    return render(request, 'procurar.html', {
        'page_title': f'Pesquisando por "{termo_procurado}" |', 
        'panos': panos,
    })

autores/templates/registro_view.html
{% extends 'parciais/base.html' %}
{% block titulo %} Registro | {% endblock titulo %}
{% block conteudo %}
<div class="main-content center container">
    <h2>Registro</h2>
</div>
<div class="main-content container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-content form-content-grid">
            {% for campos in form %}
            <div class="form-group">
                <label for="{{ campos.id_for_label }}">{{ campos.label }}</label>
                {{ campos }}
                {% if campos.help_text %}
                <p class="help_text">{{ campos.help_text }}</p>
                {% endif %}
                {{ campos.errors }}
            </div>
            {% endfor %}
        </div>
        <div class="form-group">
            <button type="submit">Enviar</button>
        </div>
    </form>
</div>
{% endblock conteudo %}

panos_de_prato/templates/categoria.html
{% extends 'parciais/base.html' %}
{% block titulo %}{{ titulo }}{% endblock %}
{% block conteudo %}
        <div class="main-content main-content-list container">
            {% for  pano in panos %}
                {% include 'parciais/panos.html' %}
            {% endfor %}
        </div>
{% endblock %}

panos_de_prato/templates/home.html
{% extends 'parciais/base.html' %}
{% block titulo %}Home | {% endblock %}
{% block conteudo %}
    <div class="main-content main-content-list container">
        {% for  pano in panos %}
            {% include 'parciais/panos.html' %}
        {% empty %}
            <div class="center m-y">
                <h1>Não há panos de prato para mostrar...</h1>
            </div>
        {% endfor %}
    </div>
{% endblock %}

panos_de_prato/templates/panos-view.html
{% extends 'parciais/base.html' %}
{% block titulo %}{{ pano.titulo }} | {% endblock %}
{% block conteudo %}
        <div class="main-content main-content-detail container">
            {% include 'parciais/panos.html' %}
        </div>
{% endblock %}

panos_de_prato/templates/parciais/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% include 'parciais/cabecalho.html' %}
    <title>{% block titulo %}{% endblock %}Panos de Prato</title>
</head>
<body>
    {% include 'parciais/titulo.html' %}
    {% include 'parciais/pesquisa.html' %}
    <main class="main-content-container">
        {% block conteudo %} {% endblock %}
        {% include 'parciais/paginacao.html' %}
    </main>
    {% include 'parciais/footer.html' %}
</body>

</html>

panos_de_prato/templates/parciais/cabecalho.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Fonte Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!--Fontes do Google-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Protest+Revolution&display=swap"
        rel="stylesheet">

    <!--<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'panos_de_prato\css\estilos.css' %}">

panos_de_prato/templates/parciais/footer.html
<footer class="main-footer">
    <div class="desenvolvedor">
        <a href="https://www.linkedin.com/in/f%C3%A1bio-moraes-13a990bb/?midSig=37hkOWTjYZzr81&eid=73o05a-lsz7vdry-hk&midToken=AQHdlwGRN3CIoA&trkEmail=eml-email_notification_digest_01-header-0-profile_glimmer-null-73o05a%7Elsz7vdry%7Ehk-null-null&trk=eml-email_notification_digest_01-header-0-profile_glimmer&originalSubdomain=br" target="_blank"  rel="noreferrer noopener">By Fábio Rodrigues de Moraes</a>
    </div>
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Projeto feito em Django</a>
        </div>
</footer>

panos_de_prato/templates/parciais/paginacao.html
{% if panos.has_other_pages %}
<div class="class container paginacao">
    <div class="class paginacao-content">
        {% if range_paginacao.primeira_pagina_fora_do_range %}
        <a class="page-link page-item" href="?page=1{{ adicional_url_query }}">1</a>
        <span class="page-item">...</span>
        {% endif %}

        {% for pagina in range_paginacao.paginacao %}
        {% if range_paginacao.pagina_atual == pagina %}
        <a class="page-link page-item pagina-atual" href="?page={{pagina}}{{ adicional_url_query }}">{{pagina}}</a>
        {% else %}
        <a class="page-link page-item" href="?page={{pagina}}{{ adicional_url_query }}">{{pagina}}</a>
        {% endif %}
        {% endfor %}

        {% if range_paginacao.ultima_pagina_fora_do_range %}
        <a class="page-link page-item" href="?page={{ range_paginacao.total_paginas }}{{ adicional_url_query }}">{{ range_paginacao.total_paginas
            }}</a>
        <span class="page-item">...</span>
        {% endif %}
    </div>
</div>
{% endif %}

panos_de_prato/templates/parciais/panos.html
<div class="panos panos-list-item">
    <div class="panos-imagem">
        <a href="{% url 'panos:pano' pano.id %}">
            <img src="{{ pano.pano_imagem.url }}" alt="Temporário">
        </a>
    </div>
    <div class="panos-title-container">
        <a href="{% url 'panos:pano' pano.id %}">
            <h2 class="panos-title">{{ pano.titulo }}</h2>
        </a>
    </div>
    <div class="panos-autor">
        <span class="panos-autor-item">
            <i class="fas fa-user"></i>
            {% if pano.autor is not None %}
                {% if pano.autor.first_name %}
                    {{ pano.autor.first_name }} {{ pano.autor.last_name }}
                {% else %}
                    {{ pano.autor.username }}
                {% endif %}
            {% else %}
                Desconhecido
            {% endif %}
        </span>
        <span class="panos-autor-item">
            <i class="fas fa-calendar-alt"></i>
            {{ pano.criado_em | date:"d/m/Y" }} às {{ pano.criado_em | date:"H:i" }}
        </span>
        {% if pano.categoria is not None %}
            <span class="panos-autor-item">
                <a href="{% url 'panos:categoria' pano.categoria.id %}">
                    <i class="fas fa-layer-group"></i>
                    {{ pano.categoria.nome }}
                </a>
            </span>
        {% endif %}
    </div>
    <div class="panos-content">
        <p>{{ pano.descricao }}</p>
    </div>
    <div class="pano-meta-container">
        <div class="panos-meta panos-preco">
            <h3 class="panos-meta-title"><i class="fas fa-coins"></i>Valor</h3>
            <div class="panos-meta-text">
                R$ {{ pano.preco }} {{ pano.unidade_preco }}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
    <footer class="panos-footer">
        <a class="panos-read-more button button-dark button-full-width" href="{% url 'panos:pano' pano.id %}">
            <i class="fas fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>
    {% endif %}
</div>

panos_de_prato/templates/parciais/pesquisa.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'panos:procurar' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ termo_procurado }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>

panos_de_prato/templates/parciais/titulo.html
<header class="main-header-container">
    <div class="main-header-container">
        <h1>
            <a class="main-logo" href="{% url 'panos:home' %}">
                <i class="fas fa-address-book main-logo-icon"></i>
                <span class="main-logo-text">Galeria de Panos de Prato</span>
            </a>
        </h1>
    </div>
</header>

panos_de_prato/templates/procurar.html
{% extends 'parciais/base.html' %}
{% block titulo %}{{ page_title }}{% endblock %}
{% block conteudo %}
        <div class="main-content main-content-list container">
            {% for  pano in panos %}
                {% include 'parciais/panos.html' %}
            {% empty %}
                <div class="center m-y">
                    <h1>Não há panos de prato para mostrar...</h1>
                </div>
            {% endfor %}
        </div>
{% endblock %}